### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by balupton** [keithamus/sort-object-keys#10]
When https://www.npmjs.com/package/sortobject did it first?

**Comment by keithamus** [comment]
@balupton I'm not sure "did it first" is a good metric for no further innovation. Multiple implementations can co-exist - and the existence of this package does not negate the validity of yours; nor vice versa.

Perhaps instead the question can be: what are the differences between the two libraries? To which I would answer:

 - This one has less dependencies. `sortobject` depends on `editions`
 - This one has less LOC
 - This one allows you to specify additional keys to sort
 - `sortobject` works with Arrays
 - `sortobject` works with other package managers
 - `sortobject` seems to have TypeScript support

I'll close this issue. Both libraries deserve to exist in the same space. They do different things and have different trade-offs.

**Comment by balupton** [comment]
Thank you Keith. That answer is very much appreciated.
